mucsci-students/2022fa-420-LigmaPy

UMLClass.py

The class and functions work. I added simple temporary comments for now.

Resolves #3

---

relationship.py

fixed missing return on line 40

missed return in if

---

test_scenarios.py

not sure if this is a bug but after the first input is passed the program crashes, I am assuming it is due to the lack of keyboard input provided. If anyone has any suggestions on how we can test the running interface please reach out

pytest -v -l --pdb --full-trace

---

UMLClass.py
relationship.py

fixed addClass ""

---

requirements.txt
saveload.py

updated saveload to drop .json if entered at end of filename.

updated saveload to return on invalid filename

---

UMLClass.py
attributes.py

Moved "Class doesn't exist" print statement so it doesn't print multiple times

Moved error messages

---

.github/workflows/codeql.yml

more automated workflowss

---

view/View.py

Its ugly, I'm sorry.
My file was a class that built all the buttons and input entries in the class itself then ran the class. Trevor's wasn't a class so nothing merged easily. I tried pulling from Trevor's files but since every widget needs to be built in the class I had to merge his file all into one file and attach 'self' to all his pieces in order to build them. 
Everything works but the file is really long and cluttered. 
I don't know a better way because I am not the best with python.

merged trevor's  buttons and my input

---

controller.py
view/ViewWithScrollBarAndOutupt.py

All button now interact with the controller
Right now the button only send a message back to the view explaining what to do with said input values.

View integrated with controller

---

controller.py
saveload.py
testRelationshipClass.py
view/View.py

fixed change param bug

---

README.md

sleep ketchup mustard

---

UMLClass.py
attributes.py
controller/cliController.py
interface/interfaceCommands.py
parameter.py
relationship.py
saveload.py

Standardized the output messages for relationships, classes, parameters, methods and fields

Error msg updates

---

controller/GuiController.py
tests/relationship_test.py
view/View.py

added comments to view and controller

---

controller/GuiController.py
controller/cliController.py
interface/interfaceCommands.py
model/UMLClass.py
model/attributes.py
model/parameter.py
model/relationship.py
model/saveload.py
tests/attributes_test.py
tests/class_test.py
tests/parameter_test.py
tests/relationship_test.py
view/View.py

class files are now in the "model" directory and refactored.

Model implementation

---

controller/cliController.py

Added new cliController

---

controller/cliController.py
requirements.txt
view/printColors.py

When I tried to run develop the imports for the cli controller were broken, so I fixed those
I'm not sure what the printColor module is but I simply commented out that import line because it doesn't seem to be used by anything at the moment. 
I also added cmd2 to the requirements text
xoxo  💋

Broken Import Fix

---

controller/cliController.py

Updated cmd2 to not process command line arguments

Fixed bug where --cli was not recognized

---

controller/GuiController.py
model/saveload.py
view/View.py

added comments to boxes and lines code

update save load to work with locations and gui

---

tests/relationship_test.py

Checks that the observer updates everything properly

Observer tests

---

model/UMLState.py
tests/attributes_test.py
tests/class_test.py
tests/undoRedo_test.py

Added test file for undo and redo

Undo redo test

---

controller/GuiController.py
view/View.py
view/exportImage.py

boxes can no longer go off left and bottom
of screen

image export now uses strategy design pattern
